name: firebase_task
description: "A new Flutter project."

publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_database: ^11.3.2
  firebase_storage: ^12.4.2
  file_picker: ^8.3.3
  chewie: ^1.10.0
  video_player: ^2.9.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_app_check: ^0.3.2+3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

 
flutter:

  uses-material-design: true

  assets:
    - assets/images/

   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
